### ISSUE TITLE
PDFs can't handle Unicode characters with built-in fonts

### ISSUE THREAD

**Issue by werebus** [umts/jobapps#313]
```
A Prawn::Errors::IncompatibleStringEncoding occurred in application_submissions#show:

  Your document includes text that's not compatible with the Windows-1252 character set.
If you need full UTF-8 support, use TTF fonts instead of PDF's built-in fonts.

  app/pdfs/print_record_pdf.rb:42:in `block in table_content'


-------------------------------
Request:
-------------------------------

  * URL        : https://transit-jobapps.admin.umass.edu/application_submissions/1933.pdf
  * HTTP Method: GET
  * IP address : 128.119.98.81
  * Parameters : {"controller"=>"application_submissions", "action"=>"show", "id"=>"1933", "format"=>"pdf"}
  * Timestamp  : 2017-11-06 07:16:27 -0500
  * Server : af-transit-app3.admin.umass.edu
  * Rails root : /srv/jobapps/releases/20170915134017
  * Process: 11273

-------------------------------
Backtrace:
-------------------------------

  app/pdfs/print_record_pdf.rb:42:in `block in table_content'
  app/pdfs/print_record_pdf.rb:41:in `table_content'
  app/pdfs/print_record_pdf.rb:11:in `initialize'
  app/controllers/application_submissions_controller.rb:97:in `new'
  app/controllers/application_submissions_controller.rb:97:in `block (2 levels) in show'
  app/controllers/application_submissions_controller.rb:94:in `show'
```

In this _particular_ case, the applicant's employer address had a `ZERO WIDTH SPACE` in it which could be stripped, but we probably should allow Unicode characters in applicant responses. Using a TrueType font with Prawn doesn't look too hard.

**Comment by werebus** [comment]
Happened again yesterday. This time — likely as a result of copy-and-pasting from a resumé ­— the problem application answer had a `'●\t'` in the middle of it.

**Comment by werebus** [comment]
See page 57 (External Fonts) in the [Prawn PDF manual](http://prawnpdf.org/manual.pdf).

**Comment by werebus** [comment]
Again last night, although the person who got the error was the applicant.
